name: Default actions
on:
  push:
    branches:
      - 'feature/**'

jobs:
  Build-check-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Check ktlint
        run: ./gradlew ktlintCheck
      - name: Test domain module
        run: ./gradlew :domain:test
      - name: Test data module
        run: ./gradlew :domain:test